# Basic
title: Zyua
subtitle: Zyua 是一个逗逼
welcome_message: <a href="https://github.com/h8452763" target="_blank">Open my github</a>
description: I love UUU
creator: <a href="https://github.com/h8452763">@onevcat</a>

url: "http://1tsky.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
   # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: href="https://github.com/h8452763
    twitter: 
    gplus: 
    mail: 920452531@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
